### ISSUE TITLE
glGetnTexImage symbol issue

### ISSUE THREAD

**Issue by luminousone** [DerelictOrg/DerelictGL3#33]
glGetnTexImage causes derelict to throw an exception, it appears this function is not supported on amd cards atm or perhaps the radeon driver is reporting the incorrect version.

I am running the new 15.7 driver for 300 series cards, and my card is a r9 390.

**Comment by aldacron** [comment]
Can you be more specific? What sort of exception? I assume you mean a SymbolLoadException. If that's the case, there's nothing I can do for you.

glGetnTexImage is part of the OpenGL 4.5 spec. Most of the functions in 4.5 also belong to an ARB or KHR extension. Given the nature of the DerelictGL3 loader, I guess one of your assumptions about the driver is correct -- the functions that belong to extensions are loading because those extensions are supported, then when the loader tries to load glGetnTexImage (which is not part of an extension), it throws because that function will not load if the context does not support 4.5.

DerelictGL3 should not be attempting to load 4.5 if the driver doesn't support it. After creating your context and calling DerelictGL3.load (but before calling reload), print the result of glGetString(GL_VERSION) and see what it says. If it starts with 4.5, then Derelict is doing its job and there's nothing I can do about it. In that case, you'll need to constrain your context creation to something less than 4.5, because something is fishy with your driver. 4.5 loads just fine for me on my Nvidia card. But if Derelict is trying to load 4.5 when the driver is reporting something else, then there's a bug somewhere in Derelict. Please let me know what you find.

On a side note, this post led me to discover that two 4.5 functions were missing, so I'm going to add them and tag a new release.

**Comment by luminousone** [comment]
glGetString(GL_VERSION) returns "4.5.13397 Compatibility Profile Context 15.200.1046.0"

when using 

wglCreateContext(window.hDC);

I will force version 4.4 via,
wglCreateContextAttribsARB(window.hDC,null,cast(int*)&attr);
This also corrects the issue, 

The radeon 300 series drivers(as of 15.7) still have the "stink" of beta on them. And after your suggestion and post I am gunna say it has to be the driver.

Anyway thanks for the help,

**Comment by ParticlePeter** [comment]
Sorry to reopen this issue, I feel my problem is closely related and want to provide additional mysteries.
Same thing on my system ( Kaveri 7800 A-10 with Radeon R7, GN 1.1), glGetnTexImage throws.
I also think that this is a quite old driver bug, even though I have the latest Drivers (Crimson Edition 15.12, and would like to report it. But before that I need some clarification:

GPU Caps Viewer and GL Extension Viewer both report full GL 4.5 support, except GLSL version (wich is 4.40). Any idea why none of the reports an issue? glGetnTexImage is not an extension, its core 4.5.

It is not possible to avoid the thrown exception with a missingSymbolCallback, what am I missing?
```
ShouldThrow missingSymFunc( string symName )  {

	// glGetnTexImage is a function added in OpenGL 4.5. My app does not use glGetnTexImage,
	// but we still want the rest of OpenGL 4.5. So if we find that glGetnTexImage is missing,
	// don't throw. This will allow OpenGL 4.5 to load - unfortunately not
	if ( symName == "glGetnTexImage" )	return ShouldThrow.No;

	// Any other missing symbol should throw.
	return ShouldThrow.Yes;
}

DerelictGL3.missingSymbolCallback = &missingSymFunc;
DerelictGL3.load();

// Throws:
// derelict.util.exception.SymbolLoadException@e:\Users\Elliot\AppData\Roaming\dub\packages\derelict-util-2.0.4\source\derelict\util\exception.d(35): Failed to load OpenGL symbol [glGetnTexImage]
```
So how can I make sure that this is a Driver Bug before reporting to ATI?

**Comment by wyrex** [comment]
SymbolLoadException happens on my R9 Fury too on Win 10 x64.
GL version: 4.5.13416 Compatibility Profile Context 15.300.1025.1001

This happens only on 4.5 functions glGetnTexImage, glGetnCompressedTexImage and glGetnUniformdv.
