### ISSUE TITLE
Error code -11

### ISSUE THREAD

**Issue by SrMordred** [DerelictOrg/DerelictGL3#54]
On Ubuntu 16.04.2 LTS
I have a HD Radeon 5600

`import derelict.opengl.gl;
void main(){
    DerelictGL3.load();
}
`
output:
Program exited with code -11

**Comment by SrMordred** [comment]
Hm I thought that was linux specific since I already played with DerelictGL on windows, but now the same code crashes on windows 10 too. (and give me object.Error@(0): Access Violation when compiled with --arch=x86)

**Comment by SrMordred** [comment]
btw using D Compiler v2.075.0

**Comment by mdparker** [comment]
Sorry, I forgot to update the README. With the new configurable loader, the way to us it is to import the package:

```
import derelict.opengl;
```
You can also configure which versions of OpenGL to support, so that if you only want 3.3, then the symbols for 4.x won't be compiled in to the binary. See [the documentation page](http://derelictorg.github.io/packages/gl3/) for details.

**Comment by SrMordred** [comment]
Nice, thanks :)
